### ISSUE TITLE
How to validate on Button Click

### ISSUE THREAD

**Issue by sarathnk** [IvanWooll/FloatingLabelValidator#2]
You have shown how to do it in UI.What if i want to validate fields on button click.

**Comment by IvanWooll** [comment]
I'm not sure if that approach makes sense for this pattern. My main motivation for combining floating labels with validation was to have the validation carried out while the user is entering text in to the fields and getting immediate feedback on whether or not their input is valid. Waiting for the user to finish filling out a form and then giving them a message seems to kind of defeat the whole point of this approach.

Can you describe a use case where you think it would be appropriate? Please include details on what would be displayed at any given moment so that I can understand your requirement.

**Comment by sarathnk** [comment]
What if the user presses the submits the wrong values in the feilds...then all the values will be passed to the server right? how can we stop that

**Comment by IvanWooll** [comment]
So you'd like to be able to check if all fields are valid before sending?

**Comment by sarathnk** [comment]
yes

**Comment by IvanWooll** [comment]
I will add a hasValidated() method to the next commit.

**Comment by sarathnk** [comment]
Ok that will be great
